language: rust
rust:
  - nightly
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install build-essential qemu nasm imagemagick
  - curl -O https://static.rust-lang.org/dist/rust-nightly-i686-unknown-linux-gnu.tar.gz
  - tar xzf rust-nightly-i686-unknown-linux-gnu.tar.gz
  - cp -R rust-nightly-i686-unknown-linux-gnu/rust-std-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu ~/rust/lib/rustlib/.
  - rm -rf rust-nightly-i686-unknown-linux-gnu rust-nightly-i686-unknown-linux-gnu.tar.gz 
script:
  - make
  - ruby .travis.rb
